import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>
        <main>
          {children}
        </main>
        <footer>
          <Footer links={[{
                  href: 'https://testdig.dk/handelsbetingelser/?srsltid=AfmBOop5OaUOveWEeMKitjEtJRS5z3IgkTCLeDo9eMTaYFLXX_gOicay',
                  text: 'Handelsbetingelser'
                }]}
                  copyright="© 2024 Din Lokale Frisør" 
              />
        </footer>
      </body>
    </html>
  );
}
